#!/bin/bash

#[ Script ]--------------------------------------------------------------------#
#                                                                              #
# dbhealth                                                                     #
#                                                                              #
# PT-br:                                                                       #
# Checa consistencia de tabelas para MySQL.                                    #
#                                                                              #
# ----------------------------                                                 #
#                                                                              #
# EN:                                                                          #
# Check table consistence for MySQL.                                           #
#                                                                              #
# reimlima@gmail.com                                                           #
# $Id: dbhealth,v 1 2015/03/13 reimlima Exp reimlima $                         #
#                                                                              #
#[ License ]-------------------------------------------------------------------#
#                                                                              #
# Copyright (c) 2015 Reinaldo Marques de Lima reimlima@gmail.com               #
#                                                                              #
# PT-br:                                                                       #
# A permissão  é  concedida,  a título gratuito, a qualquer pessoa que obtenha #
# uma   cópia   deste   software   e   arquivos   de  documentação  associados #
# (o "Software"),  para  lidar  com  o  Software sem restrição, incluindo, sem #
# limitação,  os  direitos  de  usar,  copiar,  modificar,  mesclar, publicar, #
# distribuir,  sublicenciar,  e / ou vender cópias do Software, e permitir que #
# as  pessoas  a  quem  o  Software  é fornecido o façam, sujeito às seguintes #
# condições:                                                                   #
#                                                                              #
# O  aviso de copyright acima e este aviso de permissão devem ser incluídos em #
# todas as cópias ou partes substanciais do Software.                          #
#                                                                              #
# O  SOFTWARE É FORNECIDO "COMO ESTÁ", SEM GARANTIA DE QUALQUER TIPO, EXPRESSA #
# OU  IMPLÍCITA,  INCLUINDO,  SEM  LIMITAÇÃO, AS GARANTIAS DE COMERCIALIZAÇÃO, #
# ADEQUAÇÃO  A  UM  DETERMINADO  FIM E NÃO VIOLAÇÃO. EM NENHUM CASO OS AUTORES #
# OU  DIREITOS  AUTORAIS  TITULARES  SER  RESPONSÁVEL POR QUALQUER RECLAMAÇÃO, #
# DANOS  OU  OUTRAS  RESPONSABILIDADES,  SEJA  EM  UMA  AÇÃO DE CUMPRIMENTO DE #
# CONTRATO OU DE OUTRA FORMA, DECORRENTE DE, OU EM CONEXÃO COM O SOFTWARE OU O #
# USO OU OUTRAS FUNÇÕES DO SOFTWARE.                                           #
#                                                                              #
# Exceto  conforme  contido no presente aviso, o nome do (s) dos detentores de #
# direitos  autorais acima não devem ser utilizados em publicidade ou de outra #
# forma  para  promover  a venda, uso ou outras negociações deste Software sem #
# autorização prévia por escrito.                                              #
#                                                                              #
# ----------------------------                                                 #
#                                                                              #
# EN:                                                                          #
# Permission is hereby granted, free of charge, to any person obtaining a copy #
# of  this  software  and  associated  documentation  files  (the "Software"), #
# to  deal  in  the Software without restriction, including without limitation #
# the  rights  to  use,  copy, modify, merge, publish, distribute, sublicense, #
# and/or  sell  copies  of  the  Software,  and  to permit persons to whom the #
# Software is furnished to do so, subject to the following conditions:         #
#                                                                              #
# The  above  copyright notice and this permission notice shall be included in #
# all copies or substantial portions of the Software.                          #
#                                                                              #
# THE  SOFTWARE  IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR #
# IMPLIED,  INCLUDING  BUT  NOT  LIMITED TO THE WARRANTIES OF MERCHANTABILITY, #
# FITNESS  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE #
# AUTHORS  OR  COPYRIGHT  HOLDERS  BE  LIABLE  FOR ANY CLAIM, DAMAGES OR OTHER #
# LIABILITY,   WHETHER   IN   AN   ACTION  OF  CONTRACT,  TORT  OR  OTHERWISE, #
# ARISING FROM,  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER #
# DEALINGS IN THE SOFTWARE.                                                    #
#                                                                              #
# Except  as  contained  in  this  notice,  the name(s) of the above copyright #
# holders  shall  not be used in advertising or otherwise to promote the sale, #
# use or other dealings in this Software without prior written authorization.  #
#                                                                              #
#[ Changelog ]-----------------------------------------------------------------#
#                                                                              #
#------------------------------------------------------------------------------#

#[ Variables ]-----------------------------------------------------------------#

CRASHARRAY=""
RM=$(which rm)
AWK=$(which awk)
SED=$(which sed)
GREP=$(which grep)
DATE=$(which date)
HEAD=$(which head)
BASE64=$(which base64)
SCRIPTNAME=$(basename $0)
SHA256SUM=$(which sha256sum)
MYSQLCHECKBIN=$(which mysqlcheck)
LOCKFILE=$TMPFILEPATH/${SCRIPTNAME}.lock
TMPFILENAME=$($DATE +%s | $SHA256SUM | $BASE64 | $HEAD -c 5)

# script conf file. Set here the full path like "/etc/dbhealth/dbhealth.conf"
SCRIPTCONFFILE="dbhealth.conf"

#[ Functions ]-----------------------------------------------------------------#

trapfunction(){

	# Function called by 'trap' command. Only removes lock
	# file if the process PID was the same in the file.

	PIDOFMYSELF=$$
	PIDINLOCKFILE=$(cat $LOCKFILE)
	if [ "$PIDOFMYSELF" == "$PIDINLOCKFILE" ] ; then
		rm $LOCKFILE
	else
		echo
		echo "PID: $PIDINLOCKFILE"
		echo
	fi
        
}

trap trapfunction 0 1 2 3 9 15

exiterrorfunc(){

	$RM -f $TMPFILEPATH/$TMPFILENAME
	# Generic output function, show the message given,
	# and then exits with the given code.

	# Parse message and exit code
	EXITCODE=$(echo $@ | awk '{print $NF}')
	EXITMESSAGE=$(echo $@ | awk '{ $NF = ""; print $0}')
	echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - $EXITMESSAGE" >> $DBHEALTHLOG
	exit $EXITCODE
        
}


databaseCheck(){

	echo "--------------------------------------" >> $DBHEALTHLOG
	echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - Starting Health Check execution" >> $DBHEALTHLOG
	for i in $DBARRAY; do
		$MYSQLCHECKBIN -c ${i} -u $DBUSER -p$DBPASSWORD >> $TMPFILEPATH/$TMPFILENAME
		wait
		echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - Looking for inconsistent tables in ${i} Database" >> $DBHEALTHLOG
		CRASHEDDB=$($GREP -B1 'Table is marked as crashed' $TMPFILEPATH/$TMPFILENAME | $HEAD -1 | $AWK '{print $1}')
		if [[ $CRASHEDDB = "" ]] ; then
			echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - All Tables in ${i} looks OK" >> $DBHEALTHLOG
		else
			echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - $CRASHEDDB is crashed, enqueuing to repair..." >> $DBHEALTHLOG
			CRASHARRAY="$CRASHEDDB $CRASHARRAY"
		fi
	done

	if [[ $CRASHARRAY = "" ]] ; then
		exiterrorfunc "All given databases are working fine 0"
	else
		echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - Initiating repairs" >> $DBHEALTHLOG
		databaseRepair $CRASHARRAY
	fi

}

databaseRepair(){

	IFS='
'
	for j in $CRASHARRAY; do
		DBTABLE=$(echo ${j} | $SED 's/\./ /')
		echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - Working on $DBTABLE" >> $DBHEALTHLOG
		$MYSQLCHECKBIN -r $DBTABLE -u $DBUSER -pDBPASSWORD
		if [ $? -ne 0 ] ; then
			echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - Something went wrong, you should try fix the table ${j} manually" >> $DBHEALTHLOG
		fi
	done

	exiterrorfunc "Execution ended, take a time to see the follow tables: $CRASHARRAY 0"

}

#[ Load conf file ]------------------------------------------------------------#

if [ -e $SCRIPTCONFFILE ] ; then
        source $SCRIPTCONFFILE
else
        exiterrorfunc "ERROR: $SCRIPTCONFFILE file not found 1"
fi

#[ tests, tests, tests ]-------------------------------------------------------#

# Validate if there is a lock file
if [ -e $LOCKFILE ]; then
        exiterrorfunc "There is another script running 1"
else
        echo "$$" > $LOCKFILE
fi

databaseCheck
